apiVersion: v2
name: portfolio-app
description: A Helm chart for my portfolio application
version: 0.1.3
appVersion: "1.0.0"
dependencies:
  - name: postgresql
    version: 12.1.0
    repository: https://charts.bitnami.com/bitnami