replicaCount: 3

image:
  repository: your-dockerhub-username/my-app
  tag: 1.0.0
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer 
  port: 8080      

ingress:
  enabled: true             
  className: nginx          
  host: myapp.portfolio.com   
  annotations: {}           

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
