# Image details
image:
  repository: snirrdev/portfolio
  tag: "1.0.3"  # Use Git SHA or version

# App-specific settings
app:
  port: 8080

# Kubernetes Deployment
replicaCount: 2

# Kubernetes Service
service:
  type: ClusterIP
  port: 8080

# Ingress
ingress:
  enabled: true
  className: nginx
  annotations: {}
  hosts:
    - host: portfolio.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

# Resource Limits
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi
