{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
  annotations:
    kubernetes.io/ingress.class: nginx
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{- if and .Values.service (hasKey .Values.service "name") -}}
                  {{ .Values.service.name }}
                {{- else -}}
                  {{ .Chart.Name }}
                {{- end }}
                port:
                  number: {{ .Values.service.port }}
          {{- end }}
    {{- end }}
  # {{- if .Values.ingress.tls }}
  # tls:
  #   {{- toYaml .Values.ingress.tls | nindent 4 }} # tls disabled for now
  {{- end }}
{{- end }}