{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: portfolio-app
  labels:
    app: portfolio-app
spec:
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: portfolio-app
            port:
              number: {{ .Values.service.port }}
{{- end }}
