apiVersion: v1
kind: Service
metadata:
  name: portfolio-app
  labels:
    app: portfolio-app
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.app.port }}
      protocol: TCP
  selector:
    app: portfolio-app
