apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-portfolio-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/portfolioTeamDevops/portfolio.git
    targetRevision: daniel-modernization # can you use HEAD for tracking always the last commit of the repo
    path: k8s/helm/portfolio-chart
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: portfolio-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
    