name: CI-CD

on:
  push:
    branches: 
      - main
      - k8s
  pull_request:
    branches: 
      - main
      - k8s

env:
  IMAGE_NAME: portfolio
  GO_VERSION: '1.22'

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ env.GO_VERSION }}
    
    - name: Get dependencies
      working-directory: ./app
      run: go mod download
    
    - name: Run tests
      working-directory: ./app
      run: go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./app/coverage.txt
        fail_ci_if_error: true

  build-image:
    needs: test
    runs-on: ubuntu-latest
    environment: CI_CD
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ env.GO_VERSION }}
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PAT }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: ./app
        file: ./app/Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USER }}/${{ env.IMAGE_NAME }}:latest