name: CI-CD

on:
  push:
    branches: ['*']
  pull_request:
    branches: ['*']

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'
    
    - name: Log in to GitHub Container Registry
      uses: ghcr.io/bradrydzewski/login-action@v1
      with:
        username: ${{ secrets.GHCR_TOKEN }}
        password: ${{ secrets.GHCR_USER }}
    
    - name: build and push image
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: ghcr.io/DaniNur007/portfolio
        
        
        
      
      

    