name: CI-CD

on:
  push:
    branches: [main]

env:
  IMAGE_NAME: yourdockerhubuser/go-app #once i have will update
  K8S_MANIFEST: ./k8s/deployment.yaml

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Build
      run: go build ./...

    - name: Run tests
      run: go test ./...

    - name: Lint
      run: go vet ./...