name: CI-CD

on:
  push:
    branches: ['*']
  pull_request:
    branches: ['*']

env:
  IMAGE_NAME: SnirRdev/portfolio #once i have will update
  K8S_MANIFEST: ./k8s/deployment.yaml
  docker_username: ${{ secrets.DOCKER_USERNAME }}
  docker_password: ${{ secrets.DOCKER_PASSWORD }}
  

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'
    
    - name: login to dockerhub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: build and push image
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: ${{ env.IMAGE_NAME }}
        
        
        
      
      

    