name: CI-CD

on:
  push:
    branches: 
      - main
      - k8s
  pull_request:
    branches: 
      - main
      - k8s


jobs:

  build-image:
    runs-on: ubuntu-latest
    environment: CI_CD
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'
    
    - name: login to dockerhub
      uses: docker/login-action@v3
      with:
        registry: docker.io 
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: build and push image
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: SnirRdev/portfolio
        
        
        
      
      

    