name: CI-CD

on:
  push:
    branches: 
      - main
      - daniel-modernization
  pull_request:
    branches: 
      - main
      - daniel-modernization

env:
  IMAGE_NAME: portfolio

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    
    - name: Get dependencies
      working-directory: ./app # inside the container path
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Lint with flake8
      run: flake8 .
    
    - name: Security scan with Bandit
      run: bandit -r . -s B101
    
  build-image:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PAT }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: . # repo path
        file: ./Dockerfile # repo file path
        push: true
        tags: ${{ secrets.DOCKER_USER }}/${{ env.IMAGE_NAME }}:latest