name: CI-CD

on:
  push:
    branches: 
      - main
      - k8s
  pull_request:
    branches: 
      - main
      - k8s

env:
  IMAGE_NAME: portfolio

jobs:

  build-image:
    runs-on: ubuntu-latest
    environment: CI_CD
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PAT }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: ../app/
        file: Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USER }}/${{ env.IMAGE_NAME }}:latest
    
    
        
        
      
      

    